server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ruti?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1101
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false

  # spring data jpa ??
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update #?????
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

  mvc:
    static-path-pattern: /**